apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: password
                  name: ms-courses
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: ms-courses
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
